name: Personal Web Deployment

on:
  push:
    branches:
      - development  # default branch

jobs:
  build_and_deploy:
    runs-on: [ubuntu-latest]
    if: "!startsWith(github.event.head_commit.message, 'WIP')"
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Cache pip
        uses: actions/cache@v2
        with:
          # This path is specific to Ubuntu
          path: ~/.cache/pip
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-

      - name: Install jq
        run: sudo apt-get install jq

      - name: Install dependencies
        run: pip install -r scripts/requirements.txt

      - name: Run magic script
        run: python scripts/createAllSite.py

      - name: Unignore the generated html files
        run: sed -i "s/blogs\/\*.html//g" .gitignore
      
      - name: just for testing purpose
        run: echo $(git log -1 --format=%cd sites/analogi-developer,-hacker,-user.md)

      - name: Deploy site
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_dir: ./
          publish_branch: master  # deploying branch